FROM rust:1.82-slim AS builder

WORKDIR /usr/src/app
COPY rust_app .

RUN cargo build --release

# Reuse same image to avoid glibc mismatch
FROM rust:1.82-slim

COPY --from=builder /usr/src/app/target/release/rust_app /usr/local/bin/rust_app

CMD ["rust_app"]
EXPOSE 8000
