name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Verify GCP_SA_KEY Presence
      run: |
        if [ -z "${{ secrets.GCP_SA_KEY }}" ]; then
          echo "GCP_SA_KEY is not set or is empty!"
          exit 1
        else
          echo "GCP_SA_KEY is set."
        fi
