name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3


    # Authenticate with GCP
    - name: Set up GCP authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}


    # Configure GCP project and region
    - name: Set GCP Project
      run: gcloud config set project ${{ secrets.GCP_PROJECT }}

    - name: Set GCP Region
      run: gcloud config set run/region ${{ secrets.GCP_REGION }}


    - name: Authenticate Docker with Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev



    # Build and push the Docker image to Artifact Registry
    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/arthurblattmandotdev-repo/arthurblattmandotdev
        docker build -t $IMAGE_NAME -f gcp/Dockerfile .
        docker push $IMAGE_NAME


    # Deploy the image to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy arthurblattmandotdev \
          --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/arthurblattmandotdev-repo/arthurblattmandotdev \
          --platform managed \
          --allow-unauthenticated